### ISSUE TITLE
generate more paraphrases using randomly picked exemplars

### ISSUE THREAD

**Issue by JaromAktify** [malllabiisc/SGCP#10]
I'd like to get several paraphrases for each source sentence.  Below is an approach which I attempted and an error that came up.
Modified src.txt and tgt.txt in directory: data/custom_data/test
Each sentence in src.txt was paired with 8 additional randomly picked exemplar sentences from tgt.txt - now the sizes of src.txt and tgt.txt are each 9x larger than their original size.
Here's the command I ran to generate paraphrases: python -m src.main -mode decode -dataset custom_data -run_name custom_model -gpu 0 -beam_width 10 -max_length 60 -res_file generations9x.txt
The program terminated early (snip from end of buffer below).  If this approach is possible, what steps should I take to resolve?  For example, would I need to re-run corenlp on the 'test' directory's src.txt and and tgt.txt files?

`2021-03-18 16:35:01,863 | INFO | __main__ | -------------------------
2021-03-18 16:35:01,863 | INFO | __main__ | Height: 14 

2021-03-18 16:35:01,863 | INFO | __main__ | Source Sentence: my dad found a big stack of 20s on the sidewalk in a less than desirable neighbourhood .
2021-03-18 16:35:01,863 | INFO | __main__ | Template Sentence: but it does n't do what it is designed to do ... does n't hold many brushes and does n't have 2 sides to hold water . 
2021-03-18 16:35:01,863 | INFO | __main__ | Syntactic Paraphrase: and my dad found a big stack of 20s on the sidewalk in a less than
2021-03-18 16:35:01,863 | INFO | __main__ | -------------------------
2021-03-18 16:35:01,863 | INFO | __main__ | ********************
Terminated`

**Comment by JaromAktify** [comment]
I'm re-running the model and it appears to be working ok.  Maybe I inadvertently hit an escape key last session.  I'll update when it finishes.

**Comment by JaromAktify** [comment]
The sgcp model ran successfully, however, only one paraphrase was generated per source/target pair, whereas in my ~/test directory, src.txt and tgt.txt were modified to contain 9x source/target pairs per original source sentence.

**Comment by JaromAktify** [comment]
I'm re-running sgcp, but first parsed the ~/test directory's modified src.txt and tgt.txt files using Stanford corenlp.  I'll update once the program finishes running (fingers crossed!).

**Comment by JaromAktify** [comment]
At src/clean_generations.py - line 49 modified --> ref = ' ' #refs[ref_it] ##refs disabled for sgcp_9x.py
After making this change, sgcp generations worked for randomly picked exemplars.  As a note, since gold label data was not available for randomly picked exemplars, I did not attempt to run metric functions that would require such gold labels.

**Comment by 1251480932** [comment]
> I'm re-running sgcp, but first parsed the ~/test directory's modified src.txt and tgt.txt files using Stanford corenlp. I'll update once the program finishes running (fingers crossed!).

the code con_parser I can't make the tree. The code can't connect to Stanford's servers.  how you make it  hope you can reply me thank you
