### ISSUE TITLE
Link to paper and related questions

### ISSUE THREAD

**Issue by atreyasha** [malllabiisc/SGCP#2]
Thank you for publishing code for this project! Just have some questions regarding the work.

1. I was unable to find your paper through this link on the readme. Would it be possible to provide a link for a downloadable `pdf`?

2. I would like to utilize part of your model in my personal project. I was wondering if it would be possible to forego the portion of a providing an exemplar sentence and instead provide an exemplar target syntax form? Or is the provision of the exemplar sentence a necessary part of the model?

**Comment by ashutoshml** [comment]
Hi @atreyasha ,

Thank you for your questions.

1. Please wait a few days before we provide the link for the pdf.

2. For this code, it is necessary to provide exemplar, parse it using Stanford CoreNLP and then convert to the specified format. You may have to modify the code to allow direct target syntactic form. The input to the test is governed through this [line](https://github.com/malllabiisc/SGCP/blob/f96c471f4bc3bb5671b2ff2954251708c7c448ae/src/main.py#L132)

**Comment by atreyasha** [comment]
Thank you for that, will check this out. Closing the issue.
