### ISSUE TITLE
I would like to obtain the dataset or checkpoint train of your work

### ISSUE THREAD

**Issue by thiagomonteles** [malllabiisc/SGCP#22]
Hi, I'm a student and I wanted to test your model, but the dataset is not available in the link. If you could provide me with a copy or the workout checkpoint, I would greatly appreciate it.

**Comment by ashutoshml** [comment]
The dataset should be available. Can you please check again. However, due to account migration, the models and evaluation files have been deleted. Kindly reach out to authors who have used SGCP as their baselines, incase they have a copy saved.

**Comment by thiagomonteles** [comment]
I was able to download it, thank you.
