### ISSUE TITLE
Missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by atreyasha** [malllabiisc/SGCP#4]
Hi Ashutosh,

While running the scripts for generation and evaluation, I came across some missing packages in my virtual environment; which was created using the `requirements.txt` in this repository.

The missing packages were: `pandas`, `editdistance` and `py-rouge`. Would be great if these could be added to `requirements.txt`.

**Comment by ashutoshml** [comment]
Hi @atreyasha 

Thanks for letting us know. 
Would you like to create a pull request for this? 
The `editdistance` package might be `zss`, if I am not mistaken.

**Comment by atreyasha** [comment]
Opened a PR. I had `zss` installed on my virtual environment but `import editdistance` still threw a ModuleNotFoundError.

**Comment by kabirahuja2431** [comment]
Hi Atreyasha, Thanks for bringing this issue to our attention. I have added the missing dependencies (editdistance, py-rouge and pandas) in the requirements.txt.
