### ISSUE TITLE
finally step

### ISSUE THREAD

**Issue by Zlin-111** [malllabiisc/SGCP#6]
hello，in this step，i have wrong
I have download the evaluation file: evaluation

For QQPPos:
python -m src.evaluation.eval -i Generations/QQP_Models/final_paraphrases.txt
-r data/QQPPos/test/ref.txt -t data/QQPPos/test/tgt.txt

`    stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "D:\Anaconda3\envs\new\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "D:\Anaconda3\envs\new\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './src/evaluation/apps/multi-bleu.perl -lc data/QQPPos/test/ref.txt < Generations/QQP_Models/final_paraphrases.txt' returned non-zero exit status 1.

If you suspect this is an IPython 7.17.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True`，

Thanks！！！

**Comment by ashutoshml** [comment]
This seems more like a subprocess permission issue.

Please try the following things:

1. Check if the multi-bleu.perl file is present in the correct location
2. Give executable permissions to multi-bleu.perl using `chmod +x src/evaluation/apps/multi-bleu.perl` or `chmod -R 777 src/evaluation/apps/multi-bleu.perl`

Let my know if that doesn't work. 

Also, please use beam_width = 10 when generating paraphrases i.e., when executing `python -m src.main -mode decode`

**Comment by Zlin-111** [comment]
Thank you very much. Your suggestions have solved my problem very well. Thank you!!
