### ISSUE TITLE
apply QQP_Models on custom dataset

### ISSUE THREAD

**Issue by JaromAktify** [malllabiisc/SGCP#8]
I'm working with a small dataset that is not training effectively on the SCGP model.  Would it be possible to run the pre-trained QQP_Models on a custom dataset?  I attempted this using the command below, but got a "key error" (see further below):

Command:
`python -m src.main -mode decode -dataset QQPPos -run_name QQP_Models -gpu <gpu-num> -beam_width 10 -max_length 60 -res_file generations.txt`

Terminal Output (see key error at bottom):

> COMET ERROR: The given api key NAN is invalid, please check it against the dashboard. Your experiment would not be logged 
> For more details, please refer to: https://www.comet.ml/docs/python-sdk/warnings-errors
> 2021-01-02 21:27:43,309 | INFO | __main__ | Run name: QQP_Models
> 2021-01-02 21:27:43,310 | INFO | __main__ | Test data loading..
> 2021-01-02 21:27:43,310 | INFO | __main__ | Creating Iterable Dataset
> 2021-01-02 21:27:43,311 | INFO | __main__ | Done
> 2021-01-02 21:27:43,313 | INFO | __main__ | Test data loaded!
> 2021-01-02 21:27:43,313 | INFO | __main__ | Loading Vocabulary file
> 2021-01-02 21:27:43,332 | INFO | __main__ | Vocabulary file Loaded from Models/QQP_Models/vocab.p
> 2021-01-02 21:27:43,334 | INFO | __main__ | Checkpoint found with epoch num 56
> 2021-01-02 21:27:43,335 | INFO | __main__ | Over-writing emb_size to 300 because argument use_word2vec has been set to True
> 2021-01-02 21:27:43,399 | INFO | __main__ | Initializing word vectors from pretrained model: word2vec....
> 2021-01-02 21:27:43,399 | INFO | __main__ | Please place the word2vec binary file in data/wordvecs/word2vec/GoogleNews-vectors-negative300.bin
> 2021-01-02 21:27:43,399 | INFO | __main__ | Building Encoder RNN..
> 2021-01-02 21:27:46,317 | INFO | __main__ | Encoder RNN built
> 2021-01-02 21:27:46,318 | INFO | __main__ | Building Decoder...
> 2021-01-02 21:27:46,437 | INFO | __main__ | Decoder RNN built
> 2021-01-02 21:27:46,973 | INFO | __main__ | Successfully loaded checkpoint from Models/QQP_Models/bleu-Synpar_56.pth.tar, with epoch number: 56 for train
> 2021-01-02 21:27:46,982 | INFO | __main__ | Decoding from
> 2021-01-02 21:27:46,982 | INFO | __main__ | Epoch: 56   Train loss: 808.0917673428856   Validation loss: 33.16037284721762      Validation Bleu: 35.17
> 2021-01-02 21:27:46,982 | INFO | __main__ | Test Generations
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/jarom/AvTaR/SGCP/src/main.py", line 680, in <module>
>     main()
>   File "/home/jarom/AvTaR/SGCP/src/main.py", line 677, in main
>     decode_greedy(model, test_dataloader, voc, device, args, logger)
>   File "/home/jarom/AvTaR/SGCP/src/main.py", line 381, in decode_greedy
>     is_validation=False)
>   File "/home/jarom/AvTaR/SGCP/src/model.py", line 254, in beam_decode_naive
>     leaf_embedding_list = self.treeencoder(encoder_outputs, tgt_trees)
>   File "/home/jarom/AvTaR/SGCP/SGCP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jarom/AvTaR/SGCP/src/models/treeencoder.py", line 78, in forward
>     next_input_child.append(self.voc.w2id[cur_tree[cur_node][next_child].split('-')[0]])
> KeyError: '$'
>

**Comment by ashutoshml** [comment]
Hi @JaromAktify 

Thanks for pointing this out. The model does not support domain adaptation as mentioned in the paper. That being said, I'll take a look at this issue of keyerror, and update the code repo. soon
